use tienda;

select nombre as name from producto;
select nombre as name, precio AS price from producto;
select * from producto;
select nombre as name, precio as price_eur, round(precio * 1.15,2) as price_usd from producto;
select nombre as product_name, precio as euros, round(precio * 1.15,2) as dollars from producto;
select upper(nombre), precio from producto;
select lower(nombre), precio from producto;
select nombre, upper(left(nombre,2)) from fabricante;
select nombre, round(precio) from producto;
select nombre, truncate(precio,0) from producto;
select codigo_fabricante from producto;
select distinct codigo_fabricante from producto;
select nombre as name from fabricante order by name asc;
select nombre as name from fabricante order by name desc;
select nombre from producto order by nombre asc, precio desc;
select * from fabricante limit 5;
select * from fabricante limit 3, 2;
select nombre, precio from producto order by precio asc limit 1;
select nombre, precio from producto order by precio desc limit 1;
select nombre from producto where codigo_fabricante = 2;
select p.nombre, p.precio, f.nombre as maker from producto p join fabricante f ON p.codigo_fabricante = f.codigo;
select p.nombre, p.precio, f.nombre as maker from producto p join fabricante f ON p.codigo_fabricante = f.codigo order by f.nombre asc;
select p.codigo, p.nombre, p.codigo_fabricante, f.nombre as fabricant from producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo;
select p.nombre, p.precio, f.nombre as maker from producto p join fabricante f on p.codigo_fabricante = f.codigo order by p.precio asc limit 1;
select p.nombre, p.precio, f.nombre as maker from producto p join fabricante f on p.codigo_fabricante = f.codigo order by p.precio desc limit 1;
select p.* from producto p join fabricante f on p.codigo_fabricante = f.codigo where f.nombre = 'Lenovo';
select p.* from producto p join fabricante f on p.codigo_fabricante = f.codigo where f.nombre = 'Crucial' and p.precio > 200;
select p.* from producto p join fabricante f on p.codigo_fabricante = f.codigo where f.nombre = 'Asus' or f.nombre = 'Hewlett-Packard' or f.nombre = 'Seagate';
select p.* from producto p join fabricante f on p.codigo_fabricante = f.codigo where f.nombre IN ('Asus','Hewlett-Packard','Seagate');
select p.nombre, p.precio from producto p join fabricante f on p.codigo_fabricante = f.codigo where f.nombre like '%e';
select p.nombre, p.precio from producto p join fabricante f on p.codigo_fabricante = f.codigo where f.nombre like '%w%';
select p.nombre, p.precio, f.nombre as maker from producto p join fabricante f on p.codigo_fabricante = f.codigo where p.precio >= 180 order by p.precio desc, p.nombre asc;
select distinct f.codigo, f.nombre from fabricante f join producto p on f.codigo = p.codigo_fabricante;
select f.nombre as maker, p.nombre as product from fabricante f left join producto p on f.codigo = p.codigo_fabricante;
select f.nombre from fabricante f left join producto p on f.codigo = p.codigo_fabricante where p.codigo is null;
select * from producto where codigo_fabricante = (select codigo from fabricante where nombre = 'Lenovo');
select * from producto where precio = (select max(precio) from producto where codigo_fabricante = (select codigo from fabricante where nombre = 'Lenovo'));
select p.nombre from producto p join fabricante f on p.codigo_fabricante = f.codigo where f.nombre = 'Lenovo' order by precio desc limit 1;
select p.nombre from producto p join fabricante f on p.codigo_fabricante = f.codigo where f.nombre = 'Hewlett-Packard' order by p.precio asc limit 1;
select p.* from producto p join fabricante f on p.codigo_fabricante = f.codigo join (select codigo_fabricante, max(precio) as max_price from producto group by codigo_fabricante) as m on p.codigo_fabricante = m.codigo_fabricante where f.nombre = 'Lenovo' and p.precio >= m.max_price;
select * from producto where precio >= (select max(precio) from producto where codigo_fabricante = (select codigo from fabricante where nombre = 'Lenovo'));
select * from (select p.*, f.nombre as fabricante, avg(p.precio) over (partition by f.codigo) as avg_maker from producto p inner join fabricante f on p.codigo_fabricante = f.codigo ) as r where r.fabricante = 'Asus' and r.precio > avg_maker;
